# Generated by Django 5.0.4 on 2024-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inUseCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceoNumber', models.IntegerField()),
                ('carNumber', models.IntegerField()),
            ],
        ),
    ]
