# Generated by Django 5.0.4 on 2024-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registredCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNumber', models.IntegerField()),
            ],
        ),
    ]
