# Generated by Django 5.0.4 on 2024-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0002_registredcars'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceoNumber', models.IntegerField()),
                ('ceoName', models.CharField(max_length=100)),
            ],
        ),
    ]
