# Generated by Django 5.0.4 on 2024-09-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0003_employesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employesinfo',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employesinfo',
            name='phoneNumber',
            field=models.IntegerField(default='0000000000'),
        ),
    ]
