# Generated by Django 5.0.4 on 2024-09-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0004_employesinfo_email_employesinfo_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='inusecars',
            name='instance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logsApp.employesinfo'),
        ),
    ]
