# Generated by Django 5.1.1 on 2024-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsApp', '0004_employesinfo_email_employesinfo_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiCarLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceoNumber', models.IntegerField()),
                ('ceoName', models.TextField(max_length=50)),
                ('carNumber', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
